### ISSUE TITLE
Missing `GeoJSON` prov files for `NCR`

### ISSUE THREAD

**Issue by urquico** [faeldon/philippines-json-maps#3]
## Description
I trying to create an interactive map based from leaflet and I'm testing out this project of yours and I encounter a missing GeoJSON files particularly only for NCR region. 

## Steps to reproduce
1. Click Region:
![image](https://github.com/faeldon/philippines-json-maps/assets/44643247/4fd5c633-34f4-465a-85a9-e94f827ec628)
2. Click a province 
![image](https://github.com/faeldon/philippines-json-maps/assets/44643247/c273d5c6-6cfb-4a47-859c-f3c9c7e655a3)
3. Click a municities (on the picture below, I'm clicking NCR, Second District (Not a Province))
![image](https://github.com/faeldon/philippines-json-maps/assets/44643247/2d23753c-d329-47bb-950d-fa6a09b93118)
4. Checking console (checking console reveals that the geometry has 0 length array)
![image](https://github.com/faeldon/philippines-json-maps/assets/44643247/20bcb342-a73f-444b-a0fa-f137e7d652a8)

**Expected behavior**
The expected output should show places/municities under the NCR region.

**Comment by altcoder** [comment]
There's a PSGC code mismatch for districts/province (level 2) and their cities (level 3) in NCR. This needs fixing from the shapefiles.

**Comment by altcoder** [comment]
Fixed
