### ISSUE TITLE
Davao City is not included in Davao del sur

### ISSUE THREAD

**Issue by nen02** [faeldon/philippines-json-maps#4]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/faeldon/philippines-json-maps/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
Davao City is included in regions but not in city/municipality level.
[Davao del sur](https://github.com/faeldon/philippines-json-maps/blob/master/2023/geojson/provdists/medres/municities-provdist-1102400000.0.01.json)

**Screenshots**
<img width="376" alt="image" src="https://github.com/user-attachments/assets/ec104463-1325-4921-990c-f7442a055881">

## Versions

- Node/NPM: 20
- Browser: Google Chrome

**Comment by altcoder** [comment]
Will fix this. I usually see Davao City included geographically under Davao del Sur.

Just note though that Davao City is governed and administered independently from Davao del Sur as confirmed from city and municipality list of Davao del Sur: https://psa.gov.ph/classification/psgc/citimuni/1102400000.  

Notice also that the PSGC codes show independence of Davao City to Davao del Sur administratively.

Davao City: 1130700000
Davao Del Sur: 1102400000

**Comment by altcoder** [comment]
Fixed.
